- name: Push to bikram-ops repo
  env:
    GH_TOKEN: ${{ secrets.SK_GH }}
  run: |
    git config --global user.name "bikram-ops"
    git config --global user.email "bikram@cleanomatics.com"

    git clone https://x-access-token:${SK_GH}@github.com/bikram-ops/shankarkholi.git target

    rm -rf target/*
    cp -r * target/ || true
    cp -r .[^.]* target/ || true

    cd target
    git add .
    git commit -m "sync from bikramm01" || echo "No changes"
    git push origin main --force